name: Tag Version

on:
  pull_request:
    types:
      - closed

jobs:
  tag_version:
    if: ${{ github.event.pull_request.merged }} && ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Version Type
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" =~ ^(major|minor|patch)/.*$ ]]; then
            echo "VERSION_TYPE=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "VERSION_TYPE=ignore" >> $GITHUB_ENV
            echo "Branch name does not start with major/, minor/, or patch/. Ignoring versioning."
          fi

      - name: Checkout
        if: ${{ env.VERSION_TYPE != 'ignore' }}
        uses: actions/checkout@v4

      - name: Create Version
        if: ${{ env.VERSION_TYPE != 'ignore' }}
        run: |
          chmod +x ./.github/scripts/create_tag.sh
          echo "VERSION_TAG=$(echo $(./.github/scripts/create_tag.sh ${{ env.VERSION_TYPE }}))" >> $GITHUB_ENV

      - name: Push Version
        if: ${{ env.VERSION_TYPE != 'ignore' }}
        run: |
          git config user.name "${{ secrets.GIT_USER }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          echo "VERSION_TAG=${{ env.VERSION_TAG }}"
          git tag ${{ env.VERSION_TAG }} -m "Version ${{ env.VERSION_TAG }}"
          git push origin ${{ env.VERSION_TAG }}